### ISSUE TITLE
can you support mytv the final release app name for me ？

### ISSUE THREAD

**Issue by SNull** [tommyfgj/news-video-downloader#1]
tvb jade

http://token.tvb.com/stream/live/hls/mobilehd_jade.smil?app=mytv&feed=true

tvb j2

http://token.tvb.com/stream/live/hls/mobile_hdj.smil?app=mytv&feed=true

"app=mytv",can't be used!

**Comment by tommyfgj** [comment]
The code didn't work since 2days ago. It can't retrieve the *.ts files from Akamai CDN server .
And This programme won't be updated anymore.
